<?php

/**@var Piotrek\Slider\ViewModel\Slider $sliderViewModel */
$sliderViewModel = $block->getViewModel();
$swiperId = $block->getData('swiper');
$swiper = $sliderViewModel->getSwiper($swiperId);
?>

<?php $sliders = $sliderViewModel->getSliders($swiperId) ?>

<div class="swiper sliderSwiper">
    <div class="swiper-wrapper">
        <?php foreach ($sliders as $slider): ?>
            <div class="swiper-slide"><img src="<?= $escaper->escapeUrl($sliderViewModel->getUrl($slider)) ?>"
                                           alt="<?= $escaper->escapeHtml($slider->getName()) ?>"/></div>
        <?php endforeach ?>
    </div>
    <div class="swiper-pagination"></div>
</div>

<script>
    require(['jquery', 'swiperSlide'], function ($, Swiper) {
        $(document).ready(function () {
            let swiper = new Swiper('.swiper, .sliderSwiper', {
                loop: <?= $swiper->getIsRepeated(); ?>,
                autoplay: {
                    delay: <?= $swiper->getDelay() * 1000; ?>,
                    disableOnInteraction: false
                },
                pagination: {
                    el: ".swiper-pagination",
                    clickable: true,
                },
                simulateTouch: false,
                breakpoints: {
                    1024: {
                        slidesPerView: 2,
                        spaceBetween: 40,
                    },
                    768: {
                        slidesPerView: 1,
                        spaceBetween: 30,
                    }
                },
            });
            swiper.height = 200;
        });
    });
</script>
